// <auto-generated />
using System;
using MebelMarket.SqlDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MebelMarket.Migrations
{
    [DbContext(typeof(MebelMarketContext))]
    partial class MebelMarketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MebelMarket.Domain.Furniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Furnitures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsFeatured = false,
                            IsNew = false,
                            Name = "Диван",
                            Price = 111m
                        },
                        new
                        {
                            Id = 2,
                            IsFeatured = false,
                            IsNew = false,
                            Name = "Табуреты",
                            Price = 222m
                        },
                        new
                        {
                            Id = 3,
                            IsFeatured = false,
                            IsNew = false,
                            Name = "Мойки",
                            Price = 333m
                        },
                        new
                        {
                            Id = 4,
                            IsFeatured = false,
                            IsNew = false,
                            Name = "Столешницы",
                            Price = 444m
                        },
                        new
                        {
                            Id = 5,
                            IsFeatured = false,
                            IsNew = false,
                            Name = "Кресла",
                            Price = 555m
                        },
                        new
                        {
                            Id = 6,
                            IsFeatured = false,
                            IsNew = false,
                            Name = "Кресла-качалки",
                            Price = 666m
                        },
                        new
                        {
                            Id = 7,
                            IsFeatured = false,
                            IsNew = false,
                            Name = "Пуфы",
                            Price = 777m
                        });
                });

            modelBuilder.Entity("MebelMarket.Domain.FurnitureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FurnitureTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Мягкая мебель",
                            Name = "Диваны прямые"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Мягкая мебель",
                            Name = "Диваны угловые"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Мягкая мебель",
                            Name = "Диваны для офиса"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Мягкая мебель",
                            Name = "Диваны детские"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Мягкая мебель",
                            Name = "Кресла"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Мягкая мебель",
                            Name = "Кресла-качалки"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Мягкая мебель",
                            Name = "Кресла-мешки"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Мягкая мебель",
                            Name = "Пуфы"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Мягкая мебель",
                            Name = "Банкетки"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Гостинная",
                            Name = "Стенки"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Гостинная",
                            Name = "Журнальные столики"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Гостинная",
                            Name = "Тумбы под ТВ"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Кухня",
                            Name = "Кухонные гарнитуры"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Кухня",
                            Name = "Кухонные уголки"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Кухня",
                            Name = "Кухонные столы"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Кухня",
                            Name = "Кухонные стулья"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Кухня",
                            Name = "Барные стулья"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Кухня",
                            Name = "Табуреты"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Кухня",
                            Name = "Мойки"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Кухня",
                            Name = "Столешницы"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Кухня",
                            Name = "Стеновые панели"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Кухня",
                            Name = "Комплектующие"
                        });
                });

            modelBuilder.Entity("MebelMarket.Domain.Furniture", b =>
                {
                    b.HasOne("MebelMarket.Domain.FurnitureType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
